config/routes.rb
Rails.application.routes.draw do
  get 'about/show'
  resources :about
  resources :projects
  resources :posts do
    resources :comments
  end
  root "posts#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment]).permit(:name, :comment)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :update, :edit, :destroy]

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def edit
  end

  def destroy
    @post.destroy

    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def find_post
    @post = Post.find(params[:id])
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/about/index.html.erb
<div class="card center-div" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">About Me!</h5>
      <p class="card-text">I live in Tokyo.</p>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Cras justo odio</li>
      <li class="list-group-item">Dapibus ac facilisis in</li>
      <li class="list-group-item">Vestibulum at eros</li>
    </ul>
    <div class="card-body">
      <a href="#" class="card-link">Card link</a>
      <a href="#" class="card-link">Another link</a>
    </div>
  </div>

app/views/about/show.html.erb
<%= content_for :page_title, "About Me!" %>

<div class="card center-div" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">About Me!</h5>
    <p class="card-text">I live in Tokyo.</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Cras justo odio</li>
    <li class="list-group-item">Dapibus ac facilisis in</li>
    <li class="list-group-item">Vestibulum at eros</li>
  </ul>
  <div class="card-body">
    <a href="#" class="card-link">Card link</a>
    <a href="#" class="card-link">Another link</a>
  </div>
</div>

app/views/comments/_comment.html.erb
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= comment.name %>: </strong>
          <%= comment.comment %>
        </p>
      </div>
    </div>

    <% link_to 'Delete', [comment.post, comment], method: :delete, class:
    "button is-danger", data: { confirm: "Are you sure?" } %>
  </article>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>
  <div class="field">
    <div class="control">
      <%= f.input :name, input_html: {class: 'input'}, wrapper: false,
                  label_html: {class: 'label'} %>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <%= f.input :comment, input_html: {class: 'textarea'}, wrapper: false,
                  label_html: {class: 'label'} %>
    </div>
  </div>

  <%= f.button :submit, class: "button is-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jonathans Blog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<header></header>

<section class="hero is-primary is-medium">
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to 'Jonathan Perry', root_path, class: "navbar-item" %>
          <span class="navbar-burger burger" data-target="navbarMenuHeroA">
                <span></span>
                <span></span>
                <span></span>
              </span>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end">
            <div class="navbar-item">
              <%= link_to 'Home', root_path, class: "navbar-item" %>
            </div>
              <div class="navbar-item">
              <%= link_to "Create New Post", new_post_path, class: "navbar-item" %>
            </div>
            <div class="navbar-item">
              <%= link_to "About", about_index_path, class: "navbar-item" %>
            </div>
            <div class="navbar-item">
              <%= link_to "Projects", projects_path, class: "navbar-item" %>
            </div>
            <div class="navbar-item">
              <% if signed_in? %> Signed in as: <%= current_user.email %>
                <%= button_to 'Sign out', sign_out_path, method: :delete %>
              <%
                else %> <%= link_to 'Sign in', sign_in_path %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>
  </div>

  <!-- Hero content-->
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title">
        <%= yield :page_title %>
      </h1>
    </div>
  </div>
</section>
<%= yield %>
</body>
</html>

app/views/posts/_form.html.erb
<div class="section">
  <%= simple_form_for @post do |f| %>
    <div class="field">
      <div class="control">
        <%= f.input :title, input_html: {class: 'input'}, wrapper: false,
                    label_html: {class: 'label'} %>
      </div>
    </div>
    <div class="field">
      <div class="control">
        <%= f.input :content, input_html: {class: 'textarea'}, wrapper: false,
                    label_html: {class: 'label'} %>
      </div>
    </div>

    <%= f.button :submit, class: "button is-primary" %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= content_for :page_title, "Edit post" %>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= content_for :page_title, "Welcome to my blog!" %>

<section class="section">
  <div class="container">
    <% @posts.each do |post| %>
      <div class="card">
        <div class="card-content">
          <div class="media">
            <div class="media-content">
              <p class="title is-4"> <%= link_to post.title, post %></p>
            </div>
          </div>
          <div class="content">
            <%= post.content %>
          </div>
          <div class="comment-count">
            <span class="tag is-rounded"><%# comment count %></span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/posts/new.html.erb
<%= content_for :page_title, "Create a new post" %>

<%= render 'form' %>

app/views/posts/show.html.erb
<% content_for :page_title, @post.title %>

<section class="section">
  <div class="container">
    <nav class="level">
      <div class="level-left">
        <p class="level-item">
          <strong>Actions</strong>
        </p>
      </div>

      <!-- Right side -->
      <div class="level-right">
        <p class="level-item">
          <%= link_to "Edit", edit_post_path(@post), class: "button" %>
        </p>
        <p class="level-item">
          <%= link_to "Delete", post_path(@post), method: :delete, data: {
              confirm: "Are you sure?"}, class: "button is-danger" %>
        </p>
      </div>
    </nav>
    <hr/>

    <div class="content">
      <%= @post.content %>
    </div>
  </div>
</section>

<section class="section comments">
  <div class="container">
    <h2 class="subtitle is-5"><strong><%= @post.comments.count %></strong> Comments</h2>
    <%= render @post.comments %>
    <div class="comment-form">
      <hr />
      <h3 class="subtitle is-3">Leave a reply</h3>
      <%= render 'comments/form' %>
    </div>
  </div>
</section>

app/views/projects/index.html.erb
<%= content_for :page_title, "Projects" %>

<section class="section">
  <div class="container">
    <article class="message is-medium is-primary">
      <div class="message-header">
        <p>Japan Info Jobs</p>
      </div>
      <div class="message-body">
        <p>Japan Info Jobs is a job listings site for foreigners looking for jobs in Japan. Made through the company
          <a target="_blank" href="https://jpninfo.com">Japan Info</a>.
        </p><br>
        <p>
          Check out the application <a target="_blank" href="">here</a>!
        </p>
      </div>
    </article>
  </div>
</section>